# Generated by Django 4.2.4 on 2023-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_comment_created_at_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='has_comments',
            field=models.BooleanField(default=False),
        ),
    ]
